export  const data = [
    ["AF", "+93", "Afghanistan"],
    ["AL", "+355", "Albania"],
    ["DZ", "+213", "Algeria"],
    ["AS", "+1 684", "AmericanSamoa"],
    ["AD", "+376", "Andorra"],
    ["AO", "+244", "Angola"],
    ["AI", "+1 264", "Anguilla"],
    ["AG", "+1268", "Antigua and Barbuda"],
    ["AR", "+54", "Argentina"],
    ["AM", "+374", "Armenia"],
    ["AW", "+297", "Aruba"],
    ["AU", "+61", "Australia"],
    ["AT", "+43", "Austria"],
    ["AZ", "+994", "Azerbaijan"],
    ["BS", "+1 242", "Bahamas"],
    ["BH", "+973", "Bahrain"],
    ["BD", "+880", "Bangladesh"],
    ["BB", "+1 246", "Barbados"],
    ["BY", "+375", "Belarus"],
    ["BE", "+32", "Belgium"],
    ["BZ", "+501", "Belize"],
    ["BJ", "+229", "Benin"],
    ["BM", "+1 441", "Bermuda"],
    ["BT", "+975", "Bhutan"],
    ["BA", "+387", "Bosnia and Herzegovina"],
    ["BW", "+267", "Botswana"],
    ["BR", "+55", "Brazil"],
    ["IO", "+246", "British Indian Ocean Territory"],
    ["BG", "+359", "Bulgaria"],
    ["BF", "+226", "Burkina Faso"],
    ["BI", "+257", "Burundi"],
    ["KH", "+855", "Cambodia"],
    ["CM", "+237", "Cameroon"],
    ["CA", "+1", "Canada"],
    ["CV", "+238", "Cape Verde"],
    ["KY", "+ 345", "Cayman Islands"],
    ["CF", "+236", "Central African Republic"],
    ["TD", "+235", "Chad"],
    ["CL", "+56", "Chile"],
    ["CN", "+86", "China"],
    ["CX", "+61", "Christmas Island"],
    ["CO", "+57", "Colombia"],
    ["KM", "+269", "Comoros"],
    ["CG", "+242", "Congo"],
    ["CK", "+682", "Cook Islands"],
    ["CR", "+506", "Costa Rica"],
    ["HR", "+385", "Croatia"],
    ["CU", "+53", "Cuba"],
    ["CY", "+537", "Cyprus"],
    ["CZ", "+420", "Czech Republic"],
    ["DK", "+45", "Denmark"],
    ["DJ", "+253", "Djibouti"],
    ["DM", "+1 767", "Dominica"],
    ["DO", "+1 849", "Dominican Republic"],
    ["EC", "+593", "Ecuador"],
    ["EG", "+20", "Egypt"],
    ["SV", "+503", "El Salvador"],
    ["GQ", "+240", "Equatorial Guinea"],
    ["ER", "+291", "Eritrea"],
    ["EE", "+372", "Estonia"],
    ["ET", "+251", "Ethiopia"],
    ["FO", "+298", "Faroe Islands"],
    ["FJ", "+679", "Fiji"],
    ["FI", "+358", "Finland"],
    ["FR", "+33", "France"],
    ["GF", "+594", "French Guiana"],
    ["PF", "+689", "French Polynesia"],
    ["GA", "+241", "Gabon"],
    ["GM", "+220", "Gambia"],
    ["GE", "+995", "Georgia"],
    ["DE", "+49", "Germany"],
    ["GH", "+233", "Ghana"],
    ["GI", "+350", "Gibraltar"],
    ["GR", "+30", "Greece"],
    ["GL", "+299", "Greenland"],
    ["GD", "+1 473", "Grenada"],
    ["GP", "+590", "Guadeloupe"],
    ["GU", "+1 671", "Guam"],
    ["GT", "+502", "Guatemala"],
    ["GN", "+224", "Guinea"],
    ["GW", "+245", "Guinea-Bissau"],
    ["GY", "+595", "Guyana"],
    ["HT", "+509", "Haiti"],
    ["HN", "+504", "Honduras"],
    ["HU", "+36", "Hungary"],
    ["IS", "+354", "Iceland"],
    ["IN", "+91", "India"],
    ["ID", "+62", "Indonesia"],
    ["IQ", "+964", "Iraq"],
    ["IE", "+353", "Ireland"],
    ["IL", "+972", "Israel"],
    ["IT", "+39", "Italy"],
    ["JM", "+1 876", "Jamaica"],
    ["JP", "+81", "Japan"],
    ["JO", "+962", "Jordan"],
    ["KZ", "+7 7", "Kazakhstan"],
    ["KE", "+254", "Kenya"],
    ["KI", "+686", "Kiribati"],
    ["KW", "+965", "Kuwait"],
    ["KG", "+996", "Kyrgyzstan"],
    ["LV", "+371", "Latvia"],
    ["LB", "+961", "Lebanon"],
    ["LS", "+266", "Lesotho"],
    ["LR", "+231", "Liberia"],
    ["LI", "+423", "Liechtenstein"],
    ["LT", "+370", "Lithuania"],
    ["LU", "+352", "Luxembourg"],
    ["MG", "+261", "Madagascar"],
    ["MW", "+265", "Malawi"],
    ["MY", "+60", "Malaysia"],
    ["MV", "+960", "Maldives"],
    ["ML", "+223", "Mali"],
    ["MT", "+356", "Malta"],
    ["MH", "+692", "Marshall Islands"],
    ["MQ", "+596", "Martinique"],
    ["MR", "+222", "Mauritania"],
    ["MU", "+230", "Mauritius"],
    ["YT", "+262", "Mayotte"],
    ["MX", "+52", "Mexico"],
    ["MC", "+377", "Monaco"],
    ["MN", "+976", "Mongolia"],
    ["ME", "+382", "Montenegro"],
    ["MS", "+1664", "Montserrat"],
    ["MA", "+212", "Morocco"],
    ["MM", "+95", "Myanmar"],
    ["NA", "+264", "Namibia"],
    ["NR", "+674", "Nauru"],
    ["NP", "+977", "Nepal"],
    ["NL", "+31", "Netherlands"],
    ["AN", "+599", "Netherlands Antilles"],
    ["NC", "+687", "New Caledonia"],
    ["NZ", "+64", "New Zealand"],
    ["NI", "+505", "Nicaragua"],
    ["NE", "+227", "Niger"],
    ["NG", "+234", "Nigeria"],
    ["NU", "+683", "Niue"],
    ["NF", "+672", "Norfolk Island"],
    ["MP", "+1 670", "Northern Mariana Islands"],
    ["NO", "+47", "Norway"],
    ["OM", "+968", "Oman"],
    ["PK", "+92", "Pakistan"],
    ["PW", "+680", "Palau"],
    ["PA", "+507", "Panama"],
    ["PG", "+675", "Papua New Guinea"],
    ["PY", "+595", "Paraguay"],
    ["PE", "+51", "Peru"],
    ["PH", "+63", "Philippines"],
    ["PL", "+48", "Poland"],
    ["PT", "+351", "Portugal"],
    ["PR", "+1 939", "Puerto Rico"],
    ["QA", "+974", "Qatar"],
    ["RO", "+40", "Romania"],
    ["RW", "+250", "Rwanda"],
    ["WS", "+685", "Samoa"],
    ["SM", "+378", "San Marino"],
    ["SA", "+966", "Saudi Arabia"],
    ["SN", "+221", "Senegal"],
    ["RS", "+381", "Serbia"],
    ["SC", "+248", "Seychelles"],
    ["SL", "+232", "Sierra Leone"],
    ["SG", "+65", "Singapore"],
    ["SK", "+421", "Slovakia"],
    ["SI", "+386", "Slovenia"],
    ["SB", "+677", "Solomon Islands"],
    ["ZA", "+27", "South Africa"],
    ["GS", "+500", "South Georgia and the South Sandwich Islands"],
    ["ES", "+34", "Spain"],
    ["LK", "+94", "Sri Lanka"],
    ["SD", "+249", "Sudan"],
    ["SR", "+597", "Suriname"],
    ["SZ", "+268", "Swaziland"],
    ["SE", "+46", "Sweden"],
    ["CH", "+41", "Switzerland"],
    ["TJ", "+992", "Tajikistan"],
    ["TH", "+66", "Thailand"],
    ["TG", "+228", "Togo"],
    ["TK", "+690", "Tokelau"],
    ["TO", "+676", "Tonga"],
    ["TT", "+1 868", "Trinidad and Tobago"],
    ["TN", "+216", "Tunisia"],
    ["TR", "+90", "Turkey"],
    ["TM", "+993", "Turkmenistan"],
    ["TC", "+1 649", "Turks and Caicos Islands"],
    ["TV", "+688", "Tuvalu"],
    ["UG", "+256", "Uganda"],
    ["UA", "+380", "Ukraine"],
    ["AE", "+971", "United Arab Emirates"],
    ["GB", "+44", "United Kingdom"],
    ["US", "+1", "United States"],
    ["UY", "+598", "Uruguay"],
    ["UZ", "+998", "Uzbekistan"],
    ["VU", "+678", "Vanuatu"],
    ["WF", "+681", "Wallis and Futuna"],
    ["YE", "+967", "Yemen"],
    ["ZM", "+260", "Zambia"],
    ["ZW", "+263", "Zimbabwe"],
    ["BO", "+591", "Bolivia, Plurinational State of"],
    ["BN", "+673", "Brunei Darussalam"],
    ["CC", "+61", "Cocos (Keeling) Islands"],
    ["CD", "+243", "Congo, The Democratic Republic of the"],
    ["CI", "+225", "Cote d'Ivoire"],
    ["FK", "+500", "Falkland Islands (Malvinas)"],
    ["GG", "+44", "Guernsey"],
    ["VA", "+379", "Holy See (Vatican City State)"],
    ["HK", "+852", "Hong Kong"],
    ["IR", "+98", "Iran, Islamic Republic of"],
    ["IM", "+44", "Isle of Man"],
    ["JE", "+44", "Jersey"],
    ["KP", "+850", "Korea, Democratic People's Republic of"],
    ["KR", "+82", "Korea, Republic of"],
    ["LA", "+856", "Lao People's Democratic Republic"],
    ["LY", "+218", "Libyan Arab Jamahiriya"],
    ["MO", "+853", "Macao"],
    ["MK", "+389", "Macedonia, The Former Yugoslav Republic of"],
    ["FM", "+691", "Micronesia, Federated States of"],
    ["MD", "+373", "Moldova, Republic of"],
    ["MZ", "+258", "Mozambique"],
    ["PS", "+970", "Palestinian Territory, Occupied"],
    ["PN", "+872", "Pitcairn"],
    ["RE", "+262", "Réunion"],
    ["RU", "+7", "Russia"],
    ["BL", "+590", "Saint Barthélemy"],
    ["SH", "+290", "Saint Helena, Ascension and Tristan Da Cunha"],
    ["KN", "+1 869", "Saint Kitts and Nevis"],
    ["LC", "+1 758", "Saint Lucia"],
    ["MF", "+590", "Saint Martin"],
    ["PM", "+508", "Saint Pierre and Miquelon"],
    ["VC", "+1 784", "Saint Vincent and the Grenadines"],
    ["ST", "+239", "Sao Tome and Principe"],
    ["SO", "+252", "Somalia"],
    ["SJ", "+47", "Svalbard and Jan Mayen"],
    ["SY", "+963", "Syrian Arab Republic"],
    ["TW", "+886", "Taiwan, Province of China"],
    ["TZ", "+255", "Tanzania, United Republic of"],
    ["TL", "+670", "Timor-Leste"],
    ["VE", "+58", "Venezuela, Bolivarian Republic of"],
    ["VN", "+84", "Viet Nam"],
    ["VG", "+1 284", "Virgin Islands, British"],
    ["VI", "+1 340", "Virgin Islands, U.S."]];
